services:
  postgres:
    image: postgres:16-alpine
    container_name: fintrack-postgres
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8318
    ports:
      - "5432:5432"
    volumes:
      - fintrack-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fintrack"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: fintrack-metabase
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - fintrack-metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  fintrack-postgres-data:
  fintrack-metabase-data:
